apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: ghcr.io/OOsemka/demo-app
  newTag: 8946b4c32dd57be25c58e6d86f17567a910aeef0
- name: ghcr.io/oosemka/demo-app
  newTag: latest
